image:
    name: python:3.10

include:
  - project: 'gsftech/templates/gitlab-ci'
    file: 'sonarqube-python.gitlab-ci.yml'

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHON_VER: "3.10"

stages:
  - linting
  - test
  - code quality

.install_dependencies:
  before_script:
    - python -V
    - python -m pip install poetry
    - python -m poetry config virtualenvs.in-project true
    - python -m poetry install --only main

pylint:
  stage: linting
  extends: .install_dependencies
  script:
    - pip install pylint-gitlab

    #C0301 - line-too-long
    - pylint --exit-zero -d C0301 --output-format=text:pylint_score.txt,colorized "./app"
  tags:
    - docker
  except:
    - master
    - main

pytest:
  stage: test
  extends: .install_dependencies
  script:
    - source .venv/bin/activate
    - pip install pytest pytest-asyncio pytest-cov
    - python -m pytest tests -v --cov=app --cov-report=xml:coverage-reports/coverage.xml
  artifacts:
    paths:
      - coverage-reports/
  tags:
    - docker
  except:
    - master
    - main
