name: Python Lint Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4

      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.9"

      # - name: Install poetry
      #   uses: abatilo/actions-poetry@v2

      # - name: Setup a local virtual environment (if no poetry.toml file)
      #   run: |
      #     poetry config virtualenvs.create true --local
      #     poetry config virtualenvs.in-project true --local

      # - name: Install the project dependencies
      #   run: poetry install --only main

      # - name: Export requirements.txt
      #   run: poetry export -f requirements.txt --output requirements.txt

      - name: Lint with PyLint
        uses: Silleellie/pylint-github-action@v2
        with:
          # Path of the package(s) or python file(s) to lint, relative to the repository root.
          # If more than one package (or python file) should be linted, simply specify all of them
          # with the multi-line notation like so:
          # lint-path: |
          #   src
          #   other_src
          #   main.py
          #   ...
          #
          # Required
          lint-path: app

          # Version of the Python interpreter which will install all requirements of your project
          # and lint the package(s) or python file(s) specified with the `lint-path` argument
          #
          # Required
          python-version: "3.9"

          # Path of the requirements of your project, relative to the repository root.
          # This can be easily changed in case you have `requirements-dev.txt`
          #
          # Optional, Default: requirements.txt
          # requirements-path: requirements.txt
          # requirements-path: requirements.txt
