name: Pylint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Pylint and add score to README.md
        uses: Silleellie/pylint-github-action@v2
        with:
          # Path of the package(s) or python file(s) to lint, relative to the repository root.
          # If more than one package (or python file) should be linted, simply specify all of them
          # with the multi-line notation like so:
          # lint-path: |
          #   src
          #   other_src
          #   main.py
          #   ...
          #
          # Required
          lint-path: app

          # Version of the Python interpreter which will install all requirements of your project
          # and lint the package(s) or python file(s) specified with the `lint-path` argument
          #
          # Required
          python-version: "3.9"